name: package

on:
  push:
    branches:
      - master
      - feature/actions

jobs:

  Tests_Backend:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Build Backend
      run: dotnet build -c Debug
    - name: Test Backend
      run: dotnet test ./BankingService.Tests/BankingService.Tests.csproj -c Debug
  
  Package_Backend:
    needs: Tests_Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish API
        run: dotnet publish ./BankingService.Api/BankingService.Api.csproj -c Release --runtime win-x64 -o ./PublishBackend/API
      
      - name: Publish CLI
        run: dotnet publish ./BankingService.ConsoleApp/BankingService.ConsoleApp.csproj -c Release --runtime win-x64 -o ./PublishBackend/CLI

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PublishBackend
          path: ./PublishBackend